"""``mnemos completion`` CLI subcommand — shell completion auto-install.

Generates a shell completion script for bash/zsh/fish, stores it as a file
under ``~/.mnemos/completion/`` (alongside data, vault, logs, cache), and adds
a single ``source`` line to the shell rc file. Idempotent: re-running does
not duplicate the source line and migrates away the old ``eval`` format.

File layout::

    ~/.mnemos/
      ├── data/
      ├── vault/
      ├── logs/
      ├── cache/
      └── completion/           ← generated by this command
          ├── mnemos.bash
          ├── mnemos.zsh
          └── mnemos.fish

Subcommand tree::

    mnemos completion                     — auto-detect shell + auto-install
    mnemos completion bash|zsh|fish        — explicit shell + auto-install
    mnemos completion --show-instructions — print manual steps, no file changes
"""

from __future__ import annotations

import contextlib
import os
import re
from pathlib import Path
from typing import Annotated

import typer
from rich.console import Console
from typer.completion import (  # type: ignore[attr-defined]  # typer stubs don't export this, but it exists at runtime
    get_completion_script,
)

console = Console()

completion_app = typer.Typer(
    name="completion",
    help="Install shell completion for mnemos (auto-detect + auto-install).",
    no_args_is_help=False,
)

# Env var Click/Typer uses to dispatch completion requests at runtime.
_COMPLETE_VAR = "_MNEMOS_COMPLETE"
_PROG_NAME = "mnemos"

# Shells we support for auto-install.
_SUPPORTED_SHELLS = ("bash", "zsh", "fish")


# ── Helpers ───────────────────────────────────────────────────────────────────


def _detect_shell() -> str | None:
    """Detect the current shell from ``$SHELL``.

    Returns the bare shell name (``bash``/``zsh``/``fish``) or ``None`` if
    unknown/unsupported.
    """
    raw = os.environ.get("SHELL", "")
    if not raw:
        return None
    name = raw.split("/")[-1].lower()
    if name in _SUPPORTED_SHELLS:
        return name
    return None


def _rc_path(shell: str) -> Path:
    """Return the rc file path for the given shell.

    For bash/zsh this is the rc file that receives the ``source`` line.
    For fish this is the auto-sourced completions file
    (``~/.config/fish/completions/mnemos.fish``).
    """
    home = Path.home()
    if shell == "bash":
        return home / ".bashrc"
    if shell == "zsh":
        return home / ".zshrc"
    if shell == "fish":
        return home / ".config" / "fish" / "completions" / f"{_PROG_NAME}.fish"
    raise ValueError(f"Unsupported shell: {shell}")


def _completion_file_path(shell: str) -> Path:
    """Return the path to the stored completion script for the given shell.

    All shells get a copy under ``~/.mnemos/completion/mnemos.{shell}`` for
    discoverability. Fish additionally uses the auto-sourced completions dir.
    """
    return Path.home() / ".mnemos" / "completion" / f"{_PROG_NAME}.{shell}"


def _source_line(shell: str) -> str:
    """Build the single ``source`` line to append to the rc file.

    For bash/zsh we write a guarded source line that does not error if the
    file is missing. For fish no source line is needed (fish auto-sources
    its completions directory).
    """
    if shell == "fish":
        # fish: auto-sources ~/.config/fish/completions/*.fish — no rc line.
        return ""
    path = _completion_file_path(shell)
    # Use ~ to keep the rc file portable across home directories.
    tilde_path = f"~/{path.relative_to(Path.home())}"
    return f"[ -f {tilde_path} ] && source {tilde_path}"


def _completion_script(shell: str) -> str:
    """Generate the completion script for the given shell."""
    return get_completion_script(
        prog_name=_PROG_NAME,
        complete_var=_COMPLETE_VAR,
        shell=shell,  # nosec B604 — shell is a completion type string (bash/zsh/fish), not shell=True
    )


def _is_installed(shell: str, rc: Path) -> bool:
    """Check whether an active (uncommented) source line is in the rc file.

    For fish, installation is determined by the presence of the auto-sourced
    completions file. For bash/zsh, the rc file must contain the source line
    on a line that does **not** start with ``#`` (after optional leading
    whitespace). This avoids false positives from commented-out entries.
    """
    if shell == "fish":
        return rc.exists()
    if not rc.exists():
        return False
    rel = _completion_file_path(shell).relative_to(Path.home())
    marker = f"source {rel}"
    tilde_marker = f"source ~/{rel}"
    try:
        content = rc.read_text(encoding="utf-8")
    except OSError:
        return False
    for line in content.splitlines():
        stripped = line.lstrip()
        if stripped.startswith("#"):
            continue
        if marker in line or tilde_marker in line:
            return True
    return False


def _remove_old_completion_entries(rc: Path) -> None:
    """Remove legacy ``eval "$(mnemos --show-completion ...)"`` lines.

    Strips any line containing ``mnemos --show-completion`` (commented or
    not) and the ``# Added by `mnemos completion` ...`` marker comments left
    by the old installer. This keeps the rc file clean during migration.
    """
    if not rc.exists():
        return
    try:
        content = rc.read_text(encoding="utf-8")
    except OSError:
        return
    old_marker_re = re.compile(r"mnemos --show-completion", re.IGNORECASE)
    added_by_re = re.compile(r"#\s*Added by `mnemos completion`")
    kept: list[str] = []
    for line in content.splitlines(keepends=True):
        if old_marker_re.search(line) or added_by_re.search(line):
            continue
        kept.append(line)
    new_content = "".join(kept)
    if new_content != content:
        with contextlib.suppress(OSError):
            rc.write_text(new_content, encoding="utf-8")


def _install(shell: str) -> bool:
    """Install completion for the given shell.

    Writes the completion script to ``~/.mnemos/completion/mnemos.{shell}``
    and adds a single ``source`` line to the rc file (bash/zsh). For fish,
    writes the script to the auto-sourced completions directory and a copy
    to ``~/.mnemos/completion/`` for discoverability.

    Returns True if installed (or already installed), False on write error.
    """
    rc = _rc_path(shell)
    script_file = _completion_file_path(shell)

    # Always (re)write the completion script file so it stays in sync with
    # the current mnemos version.
    try:
        script_file.parent.mkdir(parents=True, exist_ok=True)
        script_file.write_text(_completion_script(shell), encoding="utf-8")
    except OSError as exc:
        console.print(f"[red]✗ Failed to write {script_file}: {exc}[/red]")
        return False

    if shell == "fish":
        # fish: write the completion script into the auto-sourced completions
        # dir (fish sources it automatically — no rc line needed).
        try:
            rc.parent.mkdir(parents=True, exist_ok=True)
            rc.write_text(_completion_script(shell), encoding="utf-8")
        except OSError as exc:
            console.print(f"[red]✗ Failed to write {rc}: {exc}[/red]")
            return False
        console.print(f"[green]✓[/green] Installed {shell} completion → {rc}")
        console.print(f"  [dim]Copy stored at {script_file}[/dim]")
        return True

    # bash/zsh: migrate old eval-based entries, then check/install source line.
    _remove_old_completion_entries(rc)

    if _is_installed(shell, rc):
        console.print(f"[green]✓[/green] Completion for {shell} already installed at {rc}")
        return True

    line = _source_line(shell)
    try:
        rc.parent.mkdir(parents=True, exist_ok=True)
        with rc.open("a", encoding="utf-8") as fh:
            fh.write(f"\n# Added by `mnemos completion` ({shell})\n{line}\n")
    except OSError as exc:
        console.print(f"[red]✗ Failed to write {rc}: {exc}[/red]")
        return False
    console.print(f"[green]✓[/green] Installed {shell} completion → {script_file}")
    console.print(f"  [dim]Source line added to {rc}[/dim]")
    console.print(f"  [dim]Restart your shell or run: source {rc}[/dim]")
    return True


# ── Manual instructions ────────────────────────────────────────────────────────


def _print_instructions() -> None:
    """Print manual install instructions for all supported shells."""
    console.print("[bold]Manual completion installation[/bold]\n")
    for shell in _SUPPORTED_SHELLS:
        script_file = _completion_file_path(shell)
        rc = _rc_path(shell)
        if shell == "fish":
            console.print(f"[bold cyan]{shell}[/bold cyan]  →  {rc} (auto-sourced)")
            console.print(f"    Copy also stored at {script_file}")
        else:
            line = _source_line(shell)
            console.print(f"[bold cyan]{shell}[/bold cyan]  →  {script_file}")
            console.print(f"    {rc.name}: {line}")
        console.print()


# ── Command ───────────────────────────────────────────────────────────────────


@completion_app.callback(invoke_without_command=True)
def completion(
    shell: Annotated[
        str | None,
        typer.Argument(
            help="Shell to install completion for (bash/zsh/fish). "
            "If omitted, auto-detects from $SHELL.",
        ),
    ] = None,
    show_instructions: Annotated[
        bool,
        typer.Option(
            "--show-instructions",
            help="Print manual install instructions without modifying any files.",
        ),
    ] = False,
) -> None:
    """Install shell completion for mnemos.

    With no arguments: auto-detects the current shell from ``$SHELL`` and
    auto-installs the completion script into ``~/.mnemos/completion/`` plus
    a single ``source`` line in the rc file. Idempotent — re-running won't
    duplicate the source line and migrates away the old ``eval`` format.

    Pass an explicit shell (bash/zsh/fish) to override auto-detection.

    Use ``--show-instructions`` to print the manual steps for all supported
    shells without modifying any files.
    """
    if show_instructions:
        _print_instructions()
        raise typer.Exit(0)

    target = shell or _detect_shell()
    if target is None:
        console.print(
            "[red]Could not auto-detect your shell from $SHELL.[/red]\n"
            "Pass an explicit shell: [bold]mnemos completion bash|zsh|fish[/bold]\n"
            "Or see manual steps: [bold]mnemos completion --show-instructions[/bold]"
        )
        raise typer.Exit(1)

    if target not in _SUPPORTED_SHELLS:
        console.print(
            f"[red]Unsupported shell: {target!r}.[/red]\nSupported: {', '.join(_SUPPORTED_SHELLS)}"
        )
        raise typer.Exit(1)

    ok = _install(target)
    if not ok:
        raise typer.Exit(1)
